.TH "GFARM2FS" "1" "2 April 2011" "Gfarm" ""

.SH NAME
gfarm2fs \- mount a Gfarm file system

.SH SYNOPSIS
\fBgfarm2fs\fR \fBmount_point\fR [ \fBoptions\fR ]

.SH "DESCRIPTION"
.PP
gfarm2fs mounts the Gfarm file system at the specified mount point.

.SH "GENERAL OPTIONS"
.TP
\fB-h\fR
display a list of command options.
.TP
\fB-V\fR
display version.
.TP
\fB-o \fIopt,[opt...]\fB\fR
specify mount options.

.SH "GFARM2FS OPTIONS"
.TP
\fB-o syslog=\fIfacility\fB\fR
specify syslog facility.  default is local0.
.TP
\fB-o loglevel=\fIpriority\fB\fR
specify syslog priority level.  default is notice.
.TP
\fB-E \fIT\fB\fR
specify the timeout of attribute cache.  default is 1.0 seconds.
.TP
\fB-o gfs_stat_timeout=\fIT\fB\fR
same as -E option
.TP
\fB-o ncopy=\fIN\fB\fR
specify the number of copies automatically created
when a file is created.  default is 0, which means
disabling automatic replication mechanism.
.TP
\fB-o copy_limit=\fIN\fB\fR
specify the maximum number of concurrent copy
creations.  this is effective if automatic replication
is enabled.  default is 0.
.TP
\fB-o disable_genuine_nlink\fR
uses faked st_nlink (32000) of struct stat for directories.
.TP
\fB-o auto_uid_min=\fIN\fB\fR
specify the minimum UID automatically assigned.
.TP
\fB-o auto_uid_max=\fIN\fB\fR
specify the maximum UID automatically assigned.
.TP
\fB-o auto_gid_min=\fIN\fB\fR
specify the minimum GID automatically assigned.
.TP
\fB-o auto_gid_max=\fIN\fB\fR
specify the maximum GID automatically assigned.

.SH "FUSE OPTIONS"
.PP
see \fBgfarm2fs -h\fR

.SH "ENVIRONMENT VARIABLE"
.TP
\fBGFARM_CONFIG_FILE\fR
specifies the Gfarm configuration file.

.SH "NOTES"
.PP
When there is not the same local account name as the Gfarm global user
name, a temporal UID is assigned between auto_uid_min and
auto_uid_max.  When there is not the same local group name as the
Gfarm global group name, a temporal GID is assigned between
auto_gid_min and auto_gid_max.

When a temporal UID/GID cannot be assigned, setfacl(1) fails with
\fBEPERM\fR.

.SH "SECURITY NOTES"
.PP
When untrusted users are registered in the \fBgfarmroot\fR group or
\fBgfarm_root.{user,group}\fR extended attributes of any files or
directories, a Security Hole exists on the mount point of gfarm2fs
with "\fB-o suid,allow_other\fR" option executed by root (even if
either "\fB-o ro\fR" option or "\fB-o default_permissions\fR" option
is also specified).  Therefore both "\fB-o suid,allow_other\fR" option
and \fBgfarm_root.{user,group}\fR extended attributes should not be
used.

.SH "SEE ALSO"
.PP
\fBfusermount\fR(1),
\fBgfarm_attr\fR(5),
\fBgfarm2.conf\fR(5),
\fBmount\fR(8)
